# .github/workflows/publish.yml
name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cat /etc/ssl/openssl.cnf
        run: cat /etc/ssl/openssl.cnf
      - name: Overwrite openssl.cnf
        run: sudo cp .github/misc/openssl.cnf /etc/ssl/openssl.cnf
      - name: Apply openssl.cnf
        run: echo 'OPENSSL_CONF=/etc/ssl/openssl.cnf' >> $GITHUB_ENV
      - uses: r7kamura/weneedfeed-action@v3
        with:
          base_url: https://ebiebievidence.github.io/feeds
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
