# .github/workflows/publish.yml
name: publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 0 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Downgrade SECLEVEL
        run: sudo sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf
      - uses: r7kamura/weneedfeed-action@v3
        with:
          base_url: https://ebiebievidence.github.io/feeds
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
